config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete '/logout' => 'users/omniauth_callbacks#log_out'
  end

  get '/login' => 'pages#login', as: :login
  get '/profile/:id/edit' => 'users#profile', as: :edit_profile
  post '/profile/update' => 'users#profile_update', as: :profile_update
  get '/profile/:id' => 'users#show', as: :profile

  resources :posts, only: [:new, :create, :index] do
    collection do
      get ':year/:month/:day' => :index, as: :date
      get 'tagged/:tag'       => :index, as: :tagged
    end
    member do
      post :upvote
      get :outbound
    end
    resources :comments, path: 'discussion', only: [:index, :create]
  end

  resources :users, as: :account, path: :account, only: [:edit, :update] do
    member do
      get :react_test
    end
  end

  resources :users, only: [] do
    member do
      match :finish_signup, via: [:get, :patch]
    end
    resources :posts, only: [] do
      collection do
        get '/submitted' => 'posts#submitted_by_user'
        get '/liked' => 'posts#liked_by_user'
      end
    end
  end

  get '/terms-of-service' => 'pages#terms_of_service'
  get '/privacy-policy'   => 'pages#privacy_policy'
  get '/about'            => 'pages#about'
  get '/:user_id/activities' => 'users#activities', as: :user_activities

  root to: 'posts#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  devise :trackable, :omniauthable#, omniauth_providers: CONFIGURED_OMNIAUTH_PROVIDERS

  has_many :authorizations
  has_many :activities
  has_many :clicks, class_name: 'PostClick'
  has_many :posts, class_name: 'Post::Base'

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX  = /\A#{TEMP_EMAIL_PREFIX}/

  validates :email, format: { without: TEMP_EMAIL_REGEX }, on: :update
  validates :headline, presence: true, on: :update
  validates :name,     presence: true

  serialize :meta, JSON

  acts_as_voter

  friendly_id :name, use: :slugged

  scope :user_activities, -> (user_id){
                              Activity.where(user_id: user_id).joins('left join users on users.id=activities.from_user_id left join posts on posts.id=activities.post_id').select("users.id, users.name, activities.item_type, activities.post_id, posts.title, posts.is_hope, users.avatar").order("activities.id DESC")
                          }

  def first_authorization
    authorizations.first
  end

  delegate :handle, to: :first_authorization, allow_nil: true

  def self.create_from_auth!(auth)
    create! name: auth.extra.raw_info.name,
            avatar: image_from_auth(auth),
            email: "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",#email_or_temp_from_auth(auth),
            meta: auth.extra.raw_info.to_h
  end

  def self.image_from_auth(auth)
    auth.extra.raw_info.profile_image_url_https || auth.info.image
  end

  def self.email_or_temp_from_auth(auth)
    email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Authorization.find_for_oauth auth
    user     = signed_in_resource ? signed_in_resource : identity.user
    user     = create_from_auth!(auth) unless user
    identity.update_attribute :user, user if identity.user != user
    user
  end

  def email_verified?
    email && email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    #skip_before_action :check_user_signin
    
    def log_out
      reset_session
      redirect_to root_path, notice: 'You have successfully logged out.'
    end

    def twitter
      provider = 'twitter'
      @user = User.find_for_oauth(env['omniauth.auth'], current_user)
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
    
    # def self.provides_callback_for(provider)
    #   class_eval %{
    #     def #{provider}
    #       @user = User.find_for_oauth(env['omniauth.auth'], current_user)
    #       if @user.persisted?
    #         sign_in_and_redirect @user, event: :authentication
    #         set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    #       else
    #         session["devise.#{provider}_data"] = env["omniauth.auth"]
    #         redirect_to new_user_registration_url
    #       end
    #     end
    #   }
    # end


    # User.omniauth_providers.each do |provider|
    #   provides_callback_for provider
    # end

    def after_sign_in_path_for(resource)
      if resource.email_verified?
        super resource
      else
        finish_signup_user_path(resource)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    return unless request.patch? && params[:user]
    return @show_errors = true unless @user.update(user_params)
    sign_in @user, bypass: true
    redirect_to root_path, notice: 'Your profile was successfully updated.'
  end

  # GET /users/1/edit
  def edit
  end

  def show
    @user = User.find(params[:id])
    @posts = current_user.posts.order("id DESC")
  rescue
    redirect_to root_path
  end

  def react_test
    @user = User.find(params[:id])
  end

  def profile
    redirect to root_path if current_user.present? && (current_user.id != params[:id].to_i)
    @user = User.find(params[:id])
  rescue
    redirect_to root_path
  end

  def profile_update
    current_user.update_attributes(user_params)
    redirect_to root_path, notice: 'User profile has been updated successfully.'
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to account_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: account_path }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def activities
    @activities = User.user_activities(current_user.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit :email, :headline, :name
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/activities.html.slim
- if @activities.any?
  div.main_activity
	  - @activities.each do |activity|
		    div class="url activities"
		      = image_tag activity.avatar, class: 'current_user'
		      = get_activity(activity).html_safe

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/finish_signup.html.slim
.center.complete-signup
  br
  br
  h1= "Welcome to Hopes & Wishes"
  br
  p The only place where you can freely express your hopes & wishes and find like-minded people who share similar interests and have the same
   outlook on life.
  p So without further ado, welcome to the club and happy sharing :)
  br
  = form_for current_user, as: 'user', url: finish_signup_user_path(current_user), html: { role: 'form'} do |f|
    - if @show_errors && current_user.errors.any?
      #error_explanation
        - current_user.errors.full_messages.each do |msg|
          = msg
          br
    = f.text_field :email, autofocus: true, value: '', placeholder: 'E-Mail Address'
    = f.text_field :headline, autofocus: true, value: '', placeholder: 'A bit about yourself...'
    = f.submit 'Continue'

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<%#= form_for @user, url: profile_update_path do |f|%>
  <%#= f.text_field :email%>
<%# end %>
<div class="container">
  <h2 class="s-h2" style="margin-top: 2px;padding-bottom: 20px;">Settings</h2>

  <div class="settings-fields">
    <%= form_for @user, url: profile_update_path, method: :post do |f|%>
      <%= f.label "Name: "%>
      <%= f.text_field :name, style: "margin-left: 60px;margin-top:-35px;width:30%;"  %>
      <%= f.label "Email: "%>
      <%= f.text_field :email, style: "margin-left: 60px;margin-top:-35px;width:30%;" %>
      <%= f.label "About Me: "%>
      <%= f.text_field :headline, style: "margin-left: 100px;margin-top:-35px;width:70%;", data: { maxlength: '100'}, maxlength: '100' %>
      <div id="inputcounter" style="text-align: right;float:right;margin-right:265px"></div>
      <input type="submit" name="commit" value="Update" class="edit_settings button v-green" data-disable-with="Updating...">
      <% end %>
   </div>


</div>
<script type="text/javascript">
  $('#user_headline').keyup(function(){
    var value = $(this).val();
    var maxlength = $(this).data('maxlength');
    var compare = maxlength - (value.length);
    if(compare >= 0){
      compare = '<span style="color:red">*</span>' + compare
      $('#inputcounter').html(compare + 'characters left')
    }
  })
</script>

app/views/users/react_test.html.erb
<%= react_component 'DemoComponent', { name: 'display', user_name: @user.name } %>

app/views/users/show.html.erb
<div class="profile_container">
  <div>
      <% image_url = @user.avatar.gsub!(/_normal/, '') %>
      <%= image_tag image_url , class: 'twitter-rounded profle-image', height: '110', wight: '110'  %>
      <div class='title'><h1><%= @user.name.downcase %></h1></div>
      <div class='twitter_link'><a href="<%= "http://twitter.com/#{@user.meta["screen_name"]}"%>" target='_blank'><%= "@" + @user.meta["screen_name"]%></a></div>
      <div style="float:left;margin-top:45px;margin-left:-87px"><%= @user.headline %></div>
      <nav class="profile_nav">
        <ul class="profile_tab">
          <li class="page-header--navigation--tab" style="margin-left:70px">
            <a href='#' class="active" data-href="/posts?profile_tab=true&type=posts">Posted</a>
          </li>
          <li class="page-header--navigation--tab " style="float:right;margin: -24px 87px 0px 0px;">
             <a href='#' data-href="/posts?profile_tab=true&type=upvotes">Upvoted</a>
          </li>
        </ul>
        <div class="clear"></div>
      </nav>
  </div>
</div>
<ul style="margin-left: 169px;margin-top: 22px" id="tab_content">
  <%= render partial: 'posts/post', collection: @posts, locals: {profile_tab: true} %>
</ul>