config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete '/logout' => 'users/omniauth_callbacks#log_out'
  end

  get '/login' => 'pages#login', as: :login
  get '/profile/:id/edit' => 'users#profile', as: :edit_profile
  post '/profile/update' => 'users#profile_update', as: :profile_update
  get '/profile/:id' => 'users#show', as: :profile

  resources :posts, only: [:new, :create, :index] do
    collection do
      get ':year/:month/:day' => :index, as: :date
      get 'tagged/:tag'       => :index, as: :tagged
    end
    member do
      post :upvote
      get :outbound
    end
    resources :comments, path: 'discussion', only: [:index, :create]
  end

  resources :users, as: :account, path: :account, only: [:edit, :update] do
    member do
      get :react_test
    end
  end

  resources :users, only: [] do
    member do
      match :finish_signup, via: [:get, :patch]
    end
    resources :posts, only: [] do
      collection do
        get '/submitted' => 'posts#submitted_by_user'
        get '/liked' => 'posts#liked_by_user'
      end
    end
  end

  get '/terms-of-service' => 'pages#terms_of_service'
  get '/privacy-policy'   => 'pages#privacy_policy'
  get '/about'            => 'pages#about'
  get '/:user_id/activities' => 'users#activities', as: :user_activities

  root to: 'posts#index'
end

app/views/shared/_flash_notifications.html.slim
- flash.keys.each do |flash_type|
  section.flash[class=flash_type]
    .close &times;
    = flash[flash_type]

app/views/shared/_navigation.html.slim
.navigation-outer
  nav#main
    = link_to root_path do
      .brand
        .icon= 'H'
        h1= t :'community.name'
        h2= t :'Express it all.'
    ul
      - if user_signed_in?
        li= link_to 'My Profile', profile_path(id: current_user.id)
        li= link_to 'Edit Profile', edit_profile_path(id: current_user.id)
        li
          =image_tag current_user.avatar, class: 'current_user'
        li= link_to 'Log Out', logout_path, method: :delete
      - else
        li= link_to 'Log In', login_path
      li
        = link_to new_post_path, data: { secondary: true }, title: 'Add new Wish'  do
          = icon 'plus-circle'
- if user_signed_in? && !(params[:action] == 'show' && params[:controller] == 'users')
  div.tabs
    div
      = link_to 'Home', root_path, class: 'home'
      = link_to 'Activity', user_activities_path(user_id: current_user.id), class: 'activity'
      