config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete '/logout' => 'users/omniauth_callbacks#log_out'
  end

  get '/login' => 'pages#login', as: :login
  get '/profile/:id/edit' => 'users#profile', as: :edit_profile
  post '/profile/update' => 'users#profile_update', as: :profile_update
  get '/profile/:id' => 'users#show', as: :profile

  resources :posts, only: [:new, :create, :index] do
    collection do
      get ':year/:month/:day' => :index, as: :date
      get 'tagged/:tag'       => :index, as: :tagged
    end
    member do
      post :upvote
      get :outbound
    end
    resources :comments, path: 'discussion', only: [:index, :create]
  end

  resources :users, as: :account, path: :account, only: [:edit, :update] do
    member do
      get :react_test
    end
  end

  resources :users, only: [] do
    member do
      match :finish_signup, via: [:get, :patch]
    end
    resources :posts, only: [] do
      collection do
        get '/submitted' => 'posts#submitted_by_user'
        get '/liked' => 'posts#liked_by_user'
      end
    end
  end

  get '/terms-of-service' => 'pages#terms_of_service'
  get '/privacy-policy'   => 'pages#privacy_policy'
  get '/about'            => 'pages#about'
  get '/:user_id/activities' => 'users#activities', as: :user_activities

  root to: 'posts#index'
end

app/models/post/base.rb
module Post
  class Base < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: :slugged

    self.table_name = :posts

    #acts_as_taggable

    belongs_to :user
    has_many :clicks, class_name: 'PostClick', foreign_key: :post_id
    has_many :activities#, as: :item

    validates :title, presence: true
    validates :user_id, presence: true
    validates :user, presence: true

    acts_as_votable
    acts_as_commentable

    scope :on_date, ->(date) { where 'posts.created_at > ? AND posts.created_at < ?', date, date + 1.day }
  end
end

app/models/post/link.rb
module Post
  class Link < Post::Base
    #validates :url, presence: true
    #validate :url_is_valid

    def url_is_valid
      uri = URI.parse(url)
      fail 'invalid URL' unless uri.scheme == 'https' || uri.scheme == 'http'
    rescue
      errors.add :url, 'is invalid'
    end
  end
end

app/models/post/text.rb
module Post
  class Text < Post::Base
    #validates :description, presence: true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :outbound, :submitted_by_user, :liked_by_user]
  before_action :set_date, only: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :outbound, :upvote]
  before_action :set_user, only: [:submitted_by_user, :liked_by_user]

  #skip_before_action :check_user_signin

  # TODO: add pagination and infinite scroll support!
  def index
    if !params[:profile_tab].present?
      @posts = Post::Base.order('created_at DESC')

      if @date
        @posts = @posts.on_date(@date)
      end

      # if params[:tag].present?
      #   @posts = @posts.tagged_with(params[:tag])
      # end

      @posts = @posts.group_by { |p| p.created_at.to_date }
    end

    if params[:profile_tab].present? && params[:profile_tab] == 'true' && params[:type] == 'posts'
      @posts = current_user.posts.order("id DESC")
      render partial: 'posts/post', collection: @posts, locals: {profile_tab: true}, status: 200 and return
    elsif params[:profile_tab].present? && params[:profile_tab] == 'true' && params[:type] == 'upvotes'
      votes = current_user.votes.includes(:votable)
      @posts = votes.map(&:votable)
      render partial: 'posts/post', collection: @posts, locals: {profile_tab: true}, status: 200 and return
    end
  end

  def submitted_by_user
    @posts = Post::Base.where user: @user
    @posts = @posts.group_by { |p| p.created_at.to_date }
    render :index
  end

  def liked_by_user
    @posts = @user.find_up_voted_items
    render :index
  end

  def upvote
    if params[:voted] == 'false'
      current_user.up_votes(@post)
      vote = current_user.votes.last
      Activity.create!(user_id: @post.user_id, item: vote, from_user_id: current_user.id, post_id: @post.id) if current_user.id != @post.user_id
      notice = "Successfully upvoted!"
      result = { voted: true, vote_count: @post.votes_for.size }.to_json
    else
      vote = ActsAsVotable::Vote.where(voter_id: current_user.id, votable_id: @post.id).first
      ActiveRecord::Base.connection.execute("DELETE from activities where item_id = #{vote.id} and from_user_id = #{current_user.id}") if vote.present?
      vote.try(:delete)
      notice = "Successfully removed vote!"
      result = { voted: false, vote_count: @post.votes_for.size }.to_json
    end
    render json: result
    #redirect_to posts_path, notice: notice
  end

  def outbound
    @post.clicks.create! user: current_user
    redirect_to @post.url
  end

  # GET /posts/new
  def new
    @post = Post::Base.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post::Link.new post_params.merge user: current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_comments_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: post_path(@post) }
      else
        handle_post_error format, :new
      end
    end
  end

  private

  def set_date
    return unless params[:year] && params[:month] && params[:day]
    @date = Date.strptime("#{params[:year]}-#{params[:month]}-#{params[:day]}")
  end

  def handle_post_error(format, action = :edit)
    format.html { render action }
    format.json { render json: @post.errors, status: :unprocessable_entity }
  end

  def set_user
    @user = User.friendly.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post::Base.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :is_hope)
  end
end

app/views/posts/_form.html.slim
= form_for @post, as: :post, url: @post.new_record? ? posts_path : post_path(@post) do |f|
  h3
    = "Have a New"
    = f.radio_button :is_hope , false
    = "Wish"
    = f.radio_button :is_hope , true
    = "Hope ?"    

  p Express it to the world!
  br
  - if @post.errors.any?
    #error_explanation
      h4
        => pluralize(@post.errors.count, "error")
        | prohibited this post from being saved:

      ul
        - @post.errors.full_messages.each do |message|
          li= message

  = f.text_field :title, value: 'I hope', data: {maxlength: 200}, maxlength: "200"
  div id="error" style="color:red;"
  div id="inputcounter" style="text-align: right;"
  br
  = f.submit 'Express it!'

coffee:
  Wish.wish.textInputCharsLeft($('#post_title'))
  $("input[type='radio']").change ->
    if $(this).val() == 'true'
      $('.type').text('I hope');
      $('#post_title').val('I hope');
      $('#error').text('');
    else
      $('.type').text('I wish');
      $('#post_title').val('I wish');
      $('#error').text('');
    return

      

app/views/posts/_post.html.slim
- is_voted = post.votes_for.select(:voter_id).map(&:voter_id).include?(current_user.try(:id))
li.post
  .submission title="#{ is_voted ? "You have already voted this #{ post.is_hope ? 'hope' : 'wish'}"  : ""}"
    = link_to upvote_post_path(post), class: "upvote_link upvote_#{post.id}", data: {  voted: (is_voted ? true : false), post_id: post.id }, method: :post do
      .upvote
        span.upvote-link
            i class="fa fa-caret-up upvote_icon_#{post.id}" style="#{'color:green;' if is_voted}"
        div class="vote-count upvote_count_#{post.id}" style="#{ 'color:green;' if is_voted}"
          = post.votes_for.size
    .url= link_to post.title, post_comments_path(post.id), target: '_blank', class: 'post-url title'
    .description= post.description
  - unless profile_tab
    .view-discussion
      = link_to post_comments_path(post.id) do
        = icon :comment
        span.comment-count
          = post.comment_threads.count
  - else
    div.view-discussion style="float:right;margin-right:12%;margin-top:-11%"
      = link_to post_comments_path(post.id) do
        = icon :comment
        span.comment-count
          = post.comment_threads.count

app/views/posts/_tags.html.slim
- if post.tags.any?
  section.post-tags
    - post.tags.each do |tag|
      = link_to tag, tagged_posts_path(tag:tag.to_s), class: 'tag'

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.slim
- if @posts.any?
  - @posts.keys.each do |date|
    div.date
      h4.header
        = date.strftime('%B %d, %Y')
      ul= render partial: 'posts/post', collection: @posts[date], locals: {profile_tab: false}
- else
  h3.no-posts There doesn't seem to be anything here.

app/views/posts/new.html.slim
section.new-post
  = render 'form'
  = link_to 'Back', posts_path unless request.xhr?

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>